[package]
name = "day17part1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scanf = "1.2.1"
aoc = { path = "../aoc/" }

[[bin]]
name = "day17part1"
path = "main.rs"
